### ISSUE TITLE
HP max xp bug still happening 

### ISSUE THREAD

**Issue by runeliteissuesmaker** [Nightfirecat/plugin-hub-plugins#9] opened 2020-11-06 07:19 UTC
Doesn't happen every time i eat food or take damage now, but still sometimes gives me a pop up and takes a screenshot.

Could we get a toggle switch for the 200m xp notifications in general, id prefer to not have them at all anyways.

![image](https://user-images.githubusercontent.com/71134694/98337252-2ed62c00-1fbd-11eb-8e1a-c471437ee2fb.png)

**Comment by Nightfirecat** [comment] 2020-11-06 09:47
I think I will add a toggle. That said, I'm not at all sure what might cause this now since fixing the earlier issue with it. Any idea what the common root cause of it is? (loading new regions? boosting above max hp?)

**Comment by runeliteissuesmaker** [comment] 2020-11-07 10:03
no idea sorry, the first pic was triggered on first login after plugin updated, took pics of all my 200m skills

2nd pic a few minutes later happened when i ran to another area to reset agro and got attacked with a range attack

**Comment by vitorebom** [comment] 2020-11-27 18:03
I'm getting the Max xp message every other BGS spec on corp in the league, unsure if it helps

**Comment by bovfefe** [comment] 2020-12-16 02:33
to add to this and possibly help figure out the issue;

I get a max xp message whenever i start harvesting a farm patch

**Comment by Nightfirecat** [comment] 2021-01-06 15:45
Fixed in runelite/plugin-hub#928

**Closed as completed by Nightfirecat** 2021-01-06 15:45 UTC
Labels: bug, plugin: virtual-level-ups
